# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genevieve_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='myvariant_clinvar',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='variant',
            name='myvariant_exac',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='variant',
            name='myvariant_last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='chromosome',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10'), (11, b'11'), (12, b'12'), (13, b'13'), (14, b'14'), (15, b'15'), (16, b'16'), (17, b'17'), (18, b'18'), (19, b'19'), (20, b'20'), (21, b'21'), (22, b'22'), (23, b'X'), (24, b'Y'), (25, b'MT')]),
        ),
    ]
