# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genevieve_client', '0002_auto_20160319_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='myvariant_dbsnp',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
