# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genevieve_client', '0003_variant_myvariant_dbsnp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHumansUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=30)),
                ('refresh_token', models.CharField(blank=True, max_length=30)),
                ('token_expiration', models.DateTimeField(null=True)),
                ('connected_id', models.CharField(max_length=30, unique=True)),
                ('openhumans_username', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='gennoteseditor',
            name='gennotes_id',
        ),
        migrations.RemoveField(
            model_name='gennoteseditor',
            name='genome_storage_enabled',
        ),
        migrations.AddField(
            model_name='gennoteseditor',
            name='connected_id',
            field=models.CharField(default=0, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
