# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genevieve_client', '0004_auto_20160328_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenevieveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_upload_enabled', models.BooleanField(default=False)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gennoteseditor',
            name='genome_upload_enabled',
        ),
    ]
