# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genevieve_client', '0005_auto_20160329_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomereport',
            name='report_type',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
