# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genevieve_client', '0006_genomereport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomereport',
            name='genome_file_created',
            field=models.TextField(default='filler'),
            preserve_default=False,
        ),
    ]
