# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genevieve_client', '0009_auto_20160731_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomereport',
            name='report_name',
            field=models.CharField(max_length=120),
        ),
    ]
